FROM ansible/awx:15.0.1

USER root

RUN yum install -y gcc
RUN umask 0022
RUN python3 -m venv /var/lib/awx/venv/sdwan-devops
RUN /var/lib/awx/venv/sdwan-devops/bin/pip install psutil

COPY requirements.txt /tmp/requirements.txt

RUN /var/lib/awx/venv/sdwan-devops/bin/pip install --no-cache --upgrade pip setuptools wheel
RUN /var/lib/awx/venv/sdwan-devops/bin/pip install -r /tmp/requirements.txt
